<h1><?php $this->getHello();?></h1>

<h2>Fix Pay</h2>
<h3>Email = <?php $this->getEmail();?></h3>
<h3>Senha = <?php $this->getSenha();?></h3>
<h3>Brand = <?php $this->getBrand();?></h3>
<h3>MaxParcela = <?php $this->getMaxParcela();?></h3>
<h3>MinParcela = <?php $this->getMinParcela();?></h3>
<h3>BtnColor = <?php $this->getBtnColor();?></h3>
<h3>BackgroundUrl = <?php $this->getBackgroundUrl();?></h3>
